export const LISTEN_TO_CURRENT_USER_PROFILE = "LISTEN_TO_CURRENT_USER_PROFILE";
export const LISTEN_TO_PROFILE_LISTINGS = "LISTEN_TO_PROFILE_LISTINGS";
export const PROFILE_LOG_OUT = "PROFILE_LOG_OUT";
